Cvx3crv oracle data feed validation fix
yieldprotocol/vault-v2 pull request #350
Opened 2022-02-06 06:38 UTC by iamsahu

## Goal
Fixed the issue #345 reported in the code4rena competition report [136](https://github.com/code-423n4/2022-01-yield-findings/issues/136)
## Fix
Implemented data feed validation similar to what is implemented in the chainlink oracle

2022-02-07 15:27 UTC, alcueca requested changes
Minor gas thing.

2022-02-09 17:55 UTC, iamsahu commented on contracts/oracles/convex/Cvx3CrvOracle.sol
> +        require(updateTime != 0, "Incomplete round for DAI");
Auditors says the opposite.

- https://github.com/code-423n4/2022-01-yield-findings/issues/57

2022-02-14 09:29 UTC, alcueca requested changes
Please fix for consistency.

2022-02-14 09:29 UTC, alcueca commented on contracts/oracles/convex/Cvx3CrvOracle.sol
> +        require(updateTime != 0, "Incomplete round for USDC");
```suggestion
        require(updateTime > 0, "Incomplete round for USDC");
```

2022-02-14 09:29 UTC, alcueca commented on contracts/oracles/convex/Cvx3CrvOracle.sol
> +
```suggestion
        require(answeredInRound >= roundId, "Stale price for USDC");

```

2022-02-14 09:29 UTC, alcueca commented on contracts/oracles/convex/Cvx3CrvOracle.sol
> +        require(updateTime != 0, "Incomplete round for USDT");
```suggestion
        require(updateTime > 0, "Incomplete round for USDT");
```

2022-02-16 10:15 UTC, merged