ConvexYieldWrapper: removed unused named returns
yieldprotocol/vault-v2 pull request #370
Opened 2022-02-09 17:45 UTC by iamsahu

Fix for:
- https://github.com/code-423n4/2022-01-yield-findings/issues/60

2022-02-14 09:42 UTC, alcueca requested changes
We can keep the named returns, just by assigning to them.

2022-02-14 09:42 UTC, alcueca commented on contracts/oracles/convex/Cvx3CrvOracle.sol
>          return _peek(base.b6(), quote.b6(), baseAmount);
The following allows you to keep the named returns, which are nice for code parsers such as Etherscan's.
```
) external view virtual override returns (uint256 quoteAmount, uint256 updateTime) {
    (quoteAmount, updateTime) = _peek(base.b6(), quote.b6(), baseAmount);
```

2022-02-14 09:42 UTC, alcueca commented on contracts/oracles/convex/Cvx3CrvOracle.sol
> +    ) external virtual override returns (uint256, uint256) {
Same as above

2022-02-14 16:24 UTC, devtooligan approved these changes
code lgtm.  confirmed we save 3 gas per redundant return ommited

![Screen Shot 2022-02-14 at 8 23 13 AM](https://user-images.githubusercontent.com/71567643/153904085-05181d35-6432-48ee-96be-1815bf070f8a.png)

2022-02-16 09:48 UTC, alcueca approved these changes
:+1:

2022-02-16 11:16 UTC, merged