Add rewards for whomever starts an auction
yieldprotocol/vault-v2 pull request #444
Opened 2022-06-15 17:13 UTC by bbonanno

- Add gas snapshot
- Add reward for auctioneer
- Some gas golfing
- Emit event when the auction ends

2022-06-17 13:36 UTC, alcueca requested changes
The code seems functionally correct, but it can be improved in terms of clarity.

2022-06-17 13:36 UTC, alcueca commented on packages/foundry/contracts/witch/WitchV2.sol
> +        if (auction_.auctioneer != msg.sender) {
This can be removed once `_calcPayout` returns both cuts.

2022-06-17 13:36 UTC, alcueca commented on packages/foundry/contracts/witch/WitchV2.sol
> +                auctioneerCut = inkOut.wmul(auctioneerReward);
I reckon `auctioneerCut` should be calculated in `_calcPayout`, and passed to `_payInk` as a parameter.

2022-06-18 08:09 UTC, alcueca commented on packages/foundry/contracts/witch/WitchV2.sol
> +        auction_ = _calcAuction(vault, series, balances, debt, to);
My bad:

`limits[vault.ilkId][series.baseId].sum = limits_.sum + auction.ink;`

2022-06-18 08:11 UTC, alcueca commented on packages/foundry/contracts/witch/WitchDataTypes.sol
> +        bytes6 seriesId; // We cache the seriesId here
Ah, true. No, not worth it.

2022-06-20 10:51 UTC, alcueca commented on packages/foundry/contracts/witch/WitchV2.sol
> +    // ======================================================================
I would move `_auctionStarted` just after `auction`, `_auctionEnded` just after `cancel` (even if it also gets called in the `pay*` functions) and `_collateralBought` just after `_updateAccounting`. With that this block gets dissolved.

2022-06-20 10:52 UTC, alcueca approved these changes
Approved, but please move those functions as described.

2022-06-20 10:57 UTC, bbonanno commented on packages/foundry/contracts/witch/WitchV2.sol
> +        auction_ = _calcAuction(vault, series, balances, debt, to);
This is 53 gas more expensive, do you want me to do it anyway?

2022-06-20 12:50 UTC, merged