`VRWitch`
yieldprotocol/vault-v2 pull request #526
Opened 2023-02-20 07:15 UTC by iamsahu

2023-02-21 10:46 UTC, ultrasecreth requested changes
I truly believe that using inheritance like this is a no-no, better to extract the common functions into a lib and have sister witches

2023-02-22 09:53 UTC, alcueca commented
I have some blame here. The initial implementation was a completely unrelated Witch, that looked very similar. I suggested to @iamsahu to use inheritance to make peer reviews easier, not realizing that using different datatypes would mean the inheritance would be very messy.

I'm not even sure if having libraries with common functions would work that well. Few functions are actually 100% common. Maybe it makes sense to roll back to the previous implementation and having two completely unrelated witches with similar code.

2023-02-22 09:55 UTC, alcueca commented
For context, @ultrasecreth, [this was the original implementation without inheritance](https://github.com/yieldprotocol/vault-v2/pull/526/commits/11ac34d9271a2fb3bcef275abd53391bde3142a8#diff-869535c026252e8a05a06295fdbbbb0216dcc12ab4e95d9a1ec279dbd44ff789).

2023-02-23 18:48 UTC, ultrasecreth requested changes
I believe this is not the right way, majority if not all the code duplication can be eliminated by using the "template method" pattern.
Also having a lib & a base class adds more complexity for no reason, the base class makes sense cause it deals with a lot of common state, so the lib is redundant imo, the lib made sense in a context of 2 sibling contracts with no common ancestor

2023-02-24 10:51 UTC, ultrasecreth reviewed
I may be missing something, but I'm pretty sure that `WitchBase` can have like 90% of the code and then each concrete `Witch` would be just a few lines of code, but instead I see a lot of duplication that seems really unnecessary to me

2023-02-24 18:25 UTC, ultrasecreth requested changes

2023-02-24 18:25 UTC, ultrasecreth commented on packages/foundry/contracts/variable/VRWitch.sol
> +        }
this should go to a common method or maybe even better, a modifier

2023-02-24 18:25 UTC, ultrasecreth commented on packages/foundry/contracts/variable/VRWitch.sol
> +        vault = IVRCauldron(address(cauldron)).give(vaultId, address(this));
if you move this line out and make the function void, you can avoid duplicating this function

2023-02-24 18:25 UTC, ultrasecreth commented on packages/foundry/contracts/variable/VRWitch.sol
> +            DataTypes.Balances memory balances = cauldron.balances(vaultId);
if you had a template method that returns the values you get from the vault and/or series, then you can avoid duplicating this whole method. You may also be able to re-use that method to simplify more code and/or remove even more duplication on other places

2023-02-24 18:25 UTC, ultrasecreth commented on packages/foundry/contracts/WitchBase.sol
> +    {}
I don't believe you need this, each witch will be forced to have it as it should be on each one of the interfaces

2023-02-24 18:25 UTC, ultrasecreth commented on packages/foundry/contracts/WitchBase.sol
> +    {}
exactly what I was talking about :)

2023-02-24 18:25 UTC, ultrasecreth commented on packages/foundry/contracts/WitchBase.sol
> +    event AuctioneerRewardSet(uint256 auctioneerReward);
Something I recently learned is that it's better to have errors and events in the interface, 2 main reasons
- the ABI of the interface is self-sufficient
- you can split the interface in 2 (one for events and other for methods & errors) and make the tests extend the former, so you avoid duplicating events on the tests and al de headaches that that creates

2023-03-06 11:39 UTC, ultrasecreth approved these changes

2023-03-06 11:39 UTC, ultrasecreth commented on packages/foundry/contracts/Witch.sol
> +        beforeAshes
😆

2023-03-06 11:59 UTC, merged